[package]
name = "personal-memory-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
memory-public-snapshot = { path = "../../../crates/public-snapshot" }
memory-github-publication = { path = "../../../crates/github-publication" }
tokio = { version = "1", features = ["sync"] }
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
memory-engine = { path = "../../../crates/engine" }
memory-local-runtime = { path = "../../../crates/local-runtime" }
serde.workspace = true

[lints]
workspace = true
